---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: blog-app # Target namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deployer  # References the Role in 'blog-app' namespace
subjects:
- kind: ServiceAccount
  name: jenkins-deployer          # Jenkins ServiceAccount
  namespace: jenkins              # From different namespace